# Generated by Django 3.2 on 2023-06-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tittle',
            name='year',
        ),
        migrations.AddField(
            model_name='tittle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='tittle',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='reviews.Genre', verbose_name='жанр'),
        ),
        migrations.AlterField(
            model_name='tittle',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='название'),
        ),
    ]
