# Generated by Django 3.2 on 2023-06-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_tittle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tittle',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tittle',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='название'),
        ),
    ]
