# Generated by Django 3.2 on 2023-06-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230628_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tittle',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
