# Generated by Django 3.2 on 2023-07-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230704_0052'),
        ('reviews', '0005_merge_0002_auto_20230627_2156_0004_alter_tittle_genre'),
    ]

    operations = [
    ]
